
## Assignment - NumPy Introduction-1


### Q.1


In [2]:
import numpy as np

arr1 = np.array([2, 4, 6, 8, 10])
print(f"Original Array: {arr1}")

print(f"a) Addition of 2: {arr1 + 2}")
print(f"b) Multiply by 3: {arr1 * 3}")
print(f"c) Divide by 2: {arr1 / 2}")

Original Array: [ 2  4  6  8 10]
a) Addition of 2: [ 4  6  8 10 12]
b) Multiply by 3: [ 6 12 18 24 30]
c) Divide by 2: [1. 2. 3. 4. 5.]


### Q.2 Questions on Basic NumPy Array:


In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(f"Reversed Array: {reversed_arr}")

def find_most_frequent(array):
    vals, counts = np.unique(array, return_counts=True)
    max_freq = np.max(counts)
    most_freq_vals = vals[counts == max_freq]
    
    results = {}
    for val in most_freq_vals:
        indices = np.where(array == val)[0]
        results[val] = indices.tolist()
    return max_freq, results

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

freq_x, indices_x = find_most_frequent(x)
print(f"Array x most frequent value(s) and indices: {indices_x} with count {freq_x}")

freq_y, indices_y = find_most_frequent(y)
print(f"Array y most frequent value(s) and indices: {indices_y} with count {freq_y}")

Reversed Array: [5 4 6 3 2 1]
Array x most frequent value(s) and indices: {np.int64(1): [0, 5, 7, 8, 9]} with count 5
Array y most frequent value(s) and indices: {np.int64(1): [0, 1, 2], np.int64(3): [4, 8, 9]} with count 3


### Q.3 

In [4]:
arr_2d = np.array([[10, 20, 30], 
                   [40, 50, 60], 
                   [70, 80, 90]])

print(f"a) 1st row, 2nd column: {arr_2d[0, 1]}")
print(f"b) 3rd row, 1st column: {arr_2d[2, 0]}")

a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


### Q.4 

In [5]:
arr_name = np.linspace(10, 100, 25)

print(f"Array: {arr_name}\n")
print(f"Dimensions (ndim): {arr_name.ndim}")
print(f"Shape: {arr_name.shape}")
print(f"Total elements (size): {arr_name.size}")
print(f"Data type (dtype): {arr_name.dtype}")
print(f"Total bytes consumed (nbytes): {arr_name.nbytes} bytes")

transposed_reshape = arr_name.reshape(25, 1)
print(f"\nTranspose via reshape (25, 1):\n{transposed_reshape}")

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions (ndim): 1
Shape: (25,)
Total elements (size): 25
Data type (dtype): float64
Total bytes consumed (nbytes): 200 bytes

Transpose via reshape (25, 1):
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


### Q.5 

In [6]:
ucs420_student = np.array([[10, 20, 30, 40], 
                           [50, 60, 70, 80], 
                           [90, 15, 20, 35]])

print(f"Original Array:\n{ucs420_student}\n")
print(f"Mean: {np.mean(ucs420_student)}")
print(f"Median: {np.median(ucs420_student)}")
print(f"Max: {np.max(ucs420_student)}")
print(f"Min: {np.min(ucs420_student)}")
print(f"Unique elements: {np.unique(ucs420_student)}")

reshaped_ucs420_student = ucs420_student.reshape(4, 3)
print(f"\nReshaped Array (4x3):\n{reshaped_ucs420_student}")

resized_ucs420_student = np.resize(ucs420_student, (2, 3))
print(f"\nResized Array (2x3):\n{resized_ucs420_student}")

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
[[10 20 30]
 [40 50 60]]
